name: Motmautovenv
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.10
  - numpy
  - matplotlib
  - pip
  - setuptools
  - wheel
  - pip:
      - absl-py
      - astunparse
      - certifi
      - charset-normalizer
      - contourpy
      - cycler
      - filelock
      - flatbuffers
      - fonttools
      - gast
      - google-pasta
      - grpcio
      - h5py
      - idna
      - joblib
      - keras
      - kiwisolver
      - markdown
      - markdown-it-py
      - markupsafe
      - mdurl
      - ml-dtypes
      - namex
      - opt-einsum
      - optree
      - packaging
      - pillow
      - protobuf
      - pygments
      - pyparsing
      - python-dateutil
      - pyaml
      - pyyaml
      - requests
      - rich
      - scikit-learn
      - scikit-optimize
      - scipy
      - six
      - tensorboard
      - tensorflow
      - termcolor
      - threadpoolctl
      - typing_extensions
      - urllib3
      - werkzeug
      - wrapt