from setuptools import setup, find_packages
setup(
       name="Motmauto",
       version="0.2.0",
       packages=find_packages(),
       install_requires=[
        "absl-py==2.1.0",
        "astunparse==1.6.3",
        "certifi==2024.6.2",
        "charset-normalizer==3.3.2",
        "distlib==0.3.8",
        "flatbuffers==24.3.25",
        "gast==0.5.4",
        "google-pasta==0.2.0",
        "grpcio==1.64.1",
        "h5py==3.11.0",
        "idna==3.7",
        "joblib==1.4.2",
        "keras==3.3.3",
        "libclang==18.1.1",
        "Markdown==3.6",
        "markdown-it-py==3.0.0",
        "MarkupSafe==2.1.5",
        "mdurl==0.1.2",
        "ml-dtypes==0.3.2",
        "namex==0.0.8",
        "numpy==1.26.4",
        "opt-einsum==3.3.0",
        "optree==0.11.0",
        "packaging==24.0",
        "protobuf==4.25.3",
        "pyaml==24.4.0",
        "Pygments==2.18.0",
        "PyYAML==6.0.1",
        "requests==2.32.3",
        "rich==13.7.1",
        "scikit-learn==1.5.0",
        "scikit-optimize==0.10.2",
        "scipy==1.13.1",
        "six==1.16.0",
        "tensorboard==2.16.2",
        "tensorboard-data-server==0.7.2",
        "tensorflow==2.16.1",
        "tensorflow-io-gcs-filesystem==0.37.0",
        "termcolor==2.4.0",
        "threadpoolctl==3.5.0",
        "typing_extensions==4.12.2",
        "urllib3==2.2.1",
        "virtualenv==20.26.2",
        "Werkzeug==3.0.3",
        "wrapt==1.16.0",
        ],
       author="Max Weinberg",
       author_email="mweinberg@umass.edu",
       description="Refer to Readme",
       long_description=open("README.txt").read(),
       long_description_content_type="text/markdown",
       url="https://github.com/MweinbergUmass/Masters_Thesis.git",
       classifiers=[
           "Programming Language :: Python :: 3",
           "License :: OSI Approved :: MIT License",
           "Operating System :: OS Independent",
       ],
       python_requires=">=3.9",
   )