%Lets add all subfolders to the path first
addpath(genpath(pwd));
% set params
 default_model_params = struct(... 
    'sequence_length', 15, ...
    'input_shape', [15, 44], ... 
    'bottleneck_size', (22), ...
    'activation', 'selu', ...
    'conv_units', (256), ...
    'kernel_size', (3), ...
    'stride_size', (1), ...
    'batch_size', (512), ...
    'dropout_rate', 0.1, ... 
    'val_split', 0.2, ... 
    'epochs', (100), ...
    'ER_Patience', (25), ...
    'LR_patience', (10) ...
);
params = setparams(default_model_params); 
disp(params.autoenc.model_params)

project = Project('testDir', 'testDir', params); %this creates a project object which holds the data directory and the parameters and loads the python module
disp(project.dataDir)

